import {eventFactory} from "be-eventbus";

const neEventNames = {
  TABLE_CHANGE_PAGE: "TABLE_CHANGE_PAGE",
  GET_PAGE_SUCCESS: "GET_PAGE_SUCCESS",
  GET_PAGE_FAILED: "GET_PAGE_FAILED",

  SWITCH_ROW_EXPAND: "SWITCH_ROW_EXPAND",
  GET_ROW_EXPAND_DATA_SUCCESS: "GET_ROW_EXPAND_DATA_SUCCESS",
  GET_ROW_EXPAND_DATA_FAILED: "GET_ROW_EXPAND_DATA_FAILED",

  USE_CASE_CHAT_NKN_CLIENT_CONNECTED: "USE_CASE_CHAT_NKN_CLIENT_CONNECTED",
  USE_CASE_CHAT_NKN_MSG: "USE_CASE_CHAT_NKN_MSG",
  USE_CASE_CHAT_NKN_NEW_ADDRESS_SHOWN: "USE_CASE_CHAT_NKN_NEW_ADDRESS_SHOWN",
  USE_CASE_CHAT_NKN_ADDRESS_SELECTED: "USE_CASE_CHAT_NKN_ADDRESS_SELECTED",
}

const neEvents = Object.assign({
  factory: eventFactory,
}, neEventNames)

export {
  neEvents
}

